### ISSUE TITLE
[readme] Project Logo

### ISSUE THREAD

**Issue by stupidJoon** [osamhack2022/WEB_Mili-Meet_Broker#17]
# 목적
> 프로젝트 로고 만들기

**Comment by Kidprogramer1039** [comment]
> ## 목적
프로젝트 로고 만들기

**Comment by Kidprogramer1039** [comment]
목적 : 프로젝트 로고 만들기

**Comment by Kidprogramer1039** [comment]
![Mili-meet](https://user-images.githubusercontent.com/98392401/198857449-7b557dca-9f9f-46c4-95dc-52638df23f2f.png)
